name: CI-CD Pipeline (Vite React SaaS)

on:
  push:
    branches: ["main"]

jobs:

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  
  #     - name: Build and analyze
  #       uses: SonarSource/sonarqube-scan-action@v6
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # 3. DOCKER JOB
  docker:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PW }}

      #  1. Build image (no push)
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/xora:xora-v${{ github.run_number }}

      #  2. Scan with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/xora:xora-v${{ github.run_number }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      #  3. Push image ONLY if scan passes
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/xora:xora-v${{ github.run_number }}

  # 4. DEPLOY JOB
  update_deployment:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Update CD Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/akshatam-DT/gh-cd.git temp-cd
          cd temp-cd
          IMAGE="${{ secrets.DOCKER_USERNAME }}/xora:xora-v${{ github.run_number }}"

          sed -i "s|image:.*|image: ${IMAGE}|g" deployment.yaml

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add deployment.yaml
            git commit -m "Update xora image to xora-v${{ github.run_number }} [skip ci]"
            git push
          else
            echo "No changes detected in deployment.yaml"
          fi
