name: CI-CD Pipeline (Vite React SaaS)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
     
      # - name: Build and analyze
      #   uses: SonarSource/sonarqube-scan-action@v6
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
        
      - name: Build React App
        run: npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app-fe:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
           image-ref: ${{ secrets.DOCKER_USERNAME }}/app-fe:${{ github.sha }}
           format: table
           exit-code: 0
           severity: CRITICAL,HIGH

         
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app-fe:${{ github.sha }} 

      - name: Update CD Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/akshatam-DT/gh-cd.git temp-cd
          cd temp-cd
          
          # This regex finds the line starting with 'image:' and replaces everything after the ':' 
          # with your new image and the new SHA tag.
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/app-fe:${{ github.sha }}|g" deployment.yaml

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Only commit if there are actual changes to avoid the Exit Code 1 error
          if [ -n "$(git status --porcelain)" ]; then
            git add deployment.yaml
            git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
            git push
          else
            echo "No changes detected in deployment.yaml"
          fi
